include:
  - ../immich/compose.include.yaml
  - ../llama/compose.include.yaml
  - ../seaweedfs/compose.include.yaml
  - ../forgejo/compose.include.yaml
  - ../nextcloud/compose.include.yaml
  - ../grafana/compose.include.yaml
  - ../dozzle/compose.include.yaml
  - ../jellyfin/compose.include.yaml
  - ../bifrost/compose.include.yaml
  - ../open-webui/compose.include.yaml
  - ../influxdb-ui/compose.include.yaml

services:
  nginx:
    depends_on:
      - immich-server
      - s3
      - forgejo
      - open-webui
      - nextcloud
      - bifrost
      - grafana
      - dozzle
      - jellyfin
      - influxdb-ui
    hostname: nginx
    image: docker.io/library/nginx:1.30.4-alpine
    networks:
      - nginx_net
    ports:
      - "3000:3000"
      - "2283:2283"
      - "8333:8333"
      - "8080:8080"
      - "80:80"
      - "2222:2222"
      - "5650:5650"
      - "5338:5338"
      - "8888:8888"
      - "8096:8096"
      - "9211:9211"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  nginx_net:
    internal: true
