include:
  - ../influxdb/compose.include.yaml

services:
  glances:
    depends_on:
      - influxdb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    env_file:
      - .env
    hostname: glances
    image: docker.io/nicolargo/glances:ubuntu-4.3.2-full
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/rootfs:ro"
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
      - ./glances.conf:/etc/glances/glances.conf:ro
