services:
  llama-server:
    command: --models-preset /etc/llama.cpp/router.ini
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    environment:
      HF_HOME: /models
      HF_TOKEN: ${HF_TOKEN}
    hostname: llama-server
    image: ghcr.io/ggml-org/llama.cpp:server-cuda-b10630
    networks:
      - llama_net
    restart: unless-stopped
    volumes:
      - ${MODELS_PATH}:/models
      - ./router.ini:/etc/llama.cpp/router.ini:ro

networks:
  llama_net:
