services:
  dozzle:
    hostname: dozzle
    image: docker.io/amir20/dozzle:v11.1.0-alpine
    networks:
      - nginx_net
    restart: unless-stopped
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
