#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$IMMICH_DB_USERNAME" WITH PASSWORD '$IMMICH_DB_PASSWORD';
    CREATE DATABASE "$IMMICH_DB_DATABASE" OWNER "$IMMICH_DB_USERNAME";
EOSQL

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$IMMICH_DB_DATABASE" <<-EOSQL
    CREATE EXTENSION vchord CASCADE;
    CREATE EXTENSION earthdistance CASCADE;
EOSQL
