#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER "$FORGEJO_DB_USERNAME" WITH PASSWORD '$FORGEJO_DB_PASSWORD';
    CREATE DATABASE "$FORGEJO_DB_DATABASE" OWNER "$FORGEJO_DB_USERNAME";

EOSQL
