#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER "$NEXTCLOUD_DB_USERNAME" WITH PASSWORD '$NEXTCLOUD_DB_PASSWORD';
    CREATE DATABASE "$NEXTCLOUD_DB_DATABASE" OWNER "$NEXTCLOUD_DB_USERNAME";

EOSQL
